const { randomInt, randomDate } = require("./random_tools");

firstnames_list = [
  "Roberto",
  "Michael",
  "James",
  "Brandon",
  "Mitchell",
  "Jason",
  "Daniel",
  "Charles",
  "John",
  "Jonathan",
  "Nicholas",
  "David",
  "Warren",
  "Lonnie",
  "Juan",
  "Travis",
  "Dylan",
  "Matthew",
  "Jerry",
  "David",
  "Steven",
  "Zachary",
  "Edwin",
  "Francisco",
  "Thomas",
  "Bernard",
  "Jeffrey",
  "Scott",
  "Jesus",
  "Michael",
  "Gordon",
  "Brandon",
  "Omar",
  "Jason",
  "Michael",
  "Thomas",
  "John",
  "Christopher",
  "Trevor",
  "Paul",
  "Kyle",
  "Joshua",
  "Thomas",
  "Alex",
  "Michael",
  "Daniel",
  "James",
  "Christopher",
  "Connor",
  "Jeffrey",
  "Robert",
  "Marcus",
  "Matthew",
  "Jason",
  "Donald",
  "Michael",
  "Curtis",
  "Steven",
  "Matthew",
  "Eric",
  "James",
  "Aaron",
  "John",
  "Jason",
  "Cody",
  "Gabriel",
  "Christopher",
  "Joseph",
  "Stephen",
  "Raymond",
  "William",
  "Thomas",
  "John",
  "Jason",
  "Andre",
  "Shawn",
  "Alex",
  "Jeffrey",
  "Matthew",
  "Robert",
  "Thomas",
  "Mark",
  "Brian",
  "Kevin",
  "Richard",
  "Daniel",
  "Mark",
  "Anthony",
  "Daniel",
  "Philip",
  "Joseph",
  "Henry",
  "John",
  "Todd",
  "David",
  "Ricky",
  "Daniel",
  "Michael",
  "Todd",
  "Joseph",
];

lastnames_list = [
  "Murray",
  "Anderson",
  "Knapp",
  "Peterson",
  "Rollins",
  "Jones",
  "Le",
  "Campbell",
  "Campbell",
  "Ferguson",
  "Boyd",
  "Todd",
  "Harris",
  "Waters",
  "Carter",
  "Watkins",
  "Watkins",
  "Lewis",
  "Donovan",
  "Ramirez",
  "Diaz",
  "Lewis",
  "Mcdonald",
  "Wong",
  "Guerrero",
  "Dixon",
  "Castillo",
  "Fisher",
  "Taylor",
  "Potter",
  "Sanford",
  "Stephens",
  "Waters",
  "Robinson",
  "Mitchell",
  "Freeman",
  "Walker",
  "Nelson",
  "Morris",
  "Harper",
  "Thomas",
  "Shelton",
  "Soto",
  "Harris",
  "Jensen",
  "Caldwell",
  "Arnold",
  "Gonzalez",
  "Peterson",
  "Sweeney",
  "Bender",
  "Martinez",
  "Brooks",
  "Morrow",
  "Montoya",
  "Stewart",
  "Dawson",
  "Padilla",
  "Johnson",
  "Davis",
  "Hamilton",
  "Malone",
  "Flores",
  "Thomas",
  "Miller",
  "Atkinson",
  "Woods",
  "Gonzalez",
  "Cruz",
  "Poole",
  "Moss",
  "Gallagher",
  "Hood",
  "Lewis",
  "Thomas",
  "Taylor",
  "Brown",
  "Valdez",
  "Hamilton",
  "Johnson",
  "Adams",
  "Boyer",
  "Porter",
  "Butler",
  "Rodriguez",
  "Burns",
  "Blevins",
  "Gonzalez",
  "Vega",
  "Parker",
  "Shea",
  "Luna",
  "Ramsey",
  "Le",
  "Jackson",
  "Larson",
  "Swanson",
  "Jacobs",
  "Moore",
  "Miller",
];

function player_faker(teams, countries) {
  var name =
    firstnames_list[randomInt(firstnames_list.length)] +
    " " +
    lastnames_list[randomInt(lastnames_list.length)];
  var date = randomDate();
  var height = randomInt(40) + 170;
  var citizenship = countries[randomInt(countries.length)].id;
  var request_player =
    "INSERT INTO Player(name, birth, height, citizenship) VALUES (?, ?, ?, ?);SET @last_player_id = LAST_INSERT_ID();";
  var values_player = [name, date, height, citizenship];

  var team = teams[randomInt(teams.length)].id;
  var request_teamplayer =
    "INSERT INTO TeamPlayer(player, team) VALUES (@last_player_id, ?);";
  var values_teamplayer = [team];

  var request = request_player.concat(request_teamplayer);
  var values = values_player.concat(values_teamplayer);

  return { request: request, values: values };
}

function players_faker(teams, countries, number_players) {
  var request = "";
  var values = [];
  for (let i = 0; i < number_players; i++) {
    var new_player = player_faker(teams, countries);
    request = request.concat(new_player.request);
    values = values.concat(new_player.values);
  }
  return { request: request, values: values };
}

module.exports = { player_faker, players_faker };
